EGRC-469
EasyDynamics/oscal-react-library pull request #132
Opened 2021-07-20 21:50 UTC by mikeisen1

Finished subtask EGRC-469 where I migrated the data into one directory and updated test
and storybook file imports as necessary.

2021-07-20 22:50 UTC, kylelaker commented
Congratulations on getting your first PR opened in the `oscal-react-library` repo! I have re-targeted this PR to have the base branch (the branch that the PR will be merged in to) to the `EGRC-275` branch instead of `develop`. You won't need to change anything locally; this was purely a change on the GitHub side.

There are also a few things that I'd like to make sure we get cleaned up in your local git configuration including the `user.name` and `user.email` values and making sure that they're setup correctly for your repository. We can talk about a few other `git`-related things at the same time.

Love that we are able to move all this stuff into files that can be referenced from various places and deduplicate a lot of this. While everything here look good at first glance, I am going to hold off on approving until I've had a chance to look a little more closely and we've been able to work together on some of the `git` configuration items.

2021-07-21 14:37 UTC, tuckerzp commented
For the linting errors, I believe that @hreineck has had a similar issue in the past. I think the fix was to make sure you update and commit `example/package-lock.json` & `package-lock.json`. It is running `npm install` and updating those files since they are not up to date.

2021-07-21 14:47 UTC, kylelaker commented
@tuckerzp Good catch! That is #135 as well.

2021-07-21 15:10 UTC, hreineck requested changes
Awesome work, Michael! Have a few small issues to resolve but this is really great overall.

2021-07-21 15:10 UTC, hreineck commented on src/test-data/BackMatterData.js
> +          href: href,
```suggestion
          href,
```

When I run `npm run storybook` I get a linter issue here. This should fix it.

2021-07-21 15:10 UTC, hreineck commented on src/stories/OSCALModification.stories.js
>    controlId: "control-1",
```suggestion
  controlId: "control-1",
  controlPartId: "control-1_smt.a",
```

Tested this with `npm run storybook` - Without this `controlPartId` prop the icon will be invisible.

2021-07-21 15:25 UTC, mikeisen1 commented
I committed the changes suggested by @hreineck and updated the package-lock.json, but I am still getting the issues of failing the linter check.

2021-07-21 15:29 UTC, hreineck commented
> I committed the changes suggested by @hreineck and updated the package-lock.json, but I am still getting the issues of failing the linter check.

Try `npm install` and then committing package-lock.json

2021-07-21 15:32 UTC, hreineck commented
Actually, looks like it's complaining about example/package-lock.json as well. Maybe try committing the changes to that too.

2021-07-21 15:37 UTC, tuckerzp commented
> Try `npm install` and then committing package-lock.json

I am surprised that [fff7cb9](https://github.com/EasyDynamics/oscal-react-library/pull/132/commits/fff7cb96cf9514948e56dd23910f09107c1d1792) doesn't fix that.

2021-07-21 17:36 UTC, mikeisen1 commented
For the lint checks, I was initially having an issue of not being able to checkout another branch even locally. I fixed that issue, ran the npm install command in both directories,  and double-checked that the git checkout to another branch would work. That is now working locally but the lint check is still failing. Does anyone have advice on how I can resolve this?

2021-07-21 19:25 UTC, hreineck approved these changes
Awesome job!

2021-07-21 21:01 UTC, kylelaker commented
@mikeisen1 now that we've merged all the other stuff into EGRC-275, can you take one more look at everything to make sure all the data is organized correctly? I think #116 may have added more stuff

2021-07-22 15:03 UTC, kkennedy26 approved these changes
Looks good! Ran the tests and storybook, everything is functioning as expected

2021-07-22 16:46 UTC, kylelaker approved these changes

2021-07-22 16:46 UTC, merged