Show Only Skeleton When Loading Profile Viewer
EasyDynamics/oscal-react-library pull request #152
Opened 2021-08-11 19:14 UTC by hreineck

Modified the way the profile viewer loads to show only the skeleton
card when the page is loading in; this fixes the issues with the
skeleton not rendering at all, as well as making it a bit more clear
that the page is still loading content.

2021-08-12 15:01 UTC, hreineck commented
In the[previous commit](https://github.com/EasyDynamics/oscal-react-library/pull/114/commits/39b895773c3cd165b759756fbcd7ff1063215482) that initially sets up the skeleton,
there is an array of 3 skeleton cards rendered. I felt the single card looked a bit better, but if rendering multiple cards is desired that can be implemented instead.

2021-08-12 15:34 UTC, rgauss requested changes

2021-08-12 15:34 UTC, rgauss commented on src/components/OSCALProfile.js
> +          <Skeleton variant="rect" width="100%" height={115} />
Can we see what it looks like with 2 cards that only contain this 100% width `rect`?

2021-08-12 20:06 UTC, rgauss requested changes
Sorry, looked better before my terrible suggestion :worried:.

2021-08-12 21:34 UTC, rgauss approved these changes
Looks good, provided that the distribution (commands the pipeline execute) displays things properly.

2021-08-13 13:45 UTC, kkennedy26 approved these changes
Comparing the two different styles, it definitely looks better this way having the skeleton for loading imported controls instead of the whole page. Also, it isn't part of this task, but there is a console error for a key prop when running tests. I don't know if there is an issue for it already.

2021-08-13 16:51 UTC, tuckerzp commented
> Also, it isn't part of this task, but there is a console error for a key prop when running tests.

Out of curiosity, was console error there before this branch was created? Just don't want to unintentionally add errors to fix later.

2021-08-14 02:40 UTC, kkennedy26 commented
> Out of curiosity, was console error there before this branch was created? Just don't want to unintentionally add errors to fix later.

It must have been there before this branch, but not exactly sure where or when this error occurred.

2021-08-16 21:18 UTC, mikeisen1 approved these changes
This looks so much better with the skeleton rendering than without. Great work!

2021-08-19 13:55 UTC, merged