Update tibdex/github version
EasyDynamics/oscal-react-library pull request #523
Opened 2022-07-26 19:43 UTC by tuckerzp

Update the tibdex/github version as well as change some wording

2022-07-26 20:00 UTC, kylelaker approved these changes

2022-07-27 00:57 UTC, kylelaker requested changes

2022-07-27 00:57 UTC, kylelaker commented on .github/workflows/triage-pr.yml
>            private_key: ${{ secrets.APP_PRIVATE_KEY }}
```suggestion
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          permissions: >-
            {
              "pull_requests": "write"
            }
```

2022-07-27 00:57 UTC, kylelaker commented on .github/workflows/update-dependencies.yml
>            private_key: ${{ secrets.APP_PRIVATE_KEY }}
```suggestion
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write",
            }
```

2022-07-27 00:57 UTC, kylelaker commented on .github/workflows/release.yml
>            private_key: ${{ secrets.APP_PRIVATE_KEY }}
If we use this version, we should use the new permissions scoping feature that came with it.

https://github.com/tibdex/github-app-token/blob/f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06/action.yml#L15-L16

```suggestion
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          permissions: >-
            {
              "contents": "write"
            }
```

2022-07-27 00:57 UTC, kylelaker commented on .github/workflows/release.yml
> +        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
Here (and everywhere), can we add a comment that explains what version this maps to? We should have done that before...

```suggestion
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # v1.6.0
```

Also, feel free to tell me that we should consider just using the `release/v1.6` branch. We had that discussion on the PR where this was originally introduced so before starting a convo, please read the earlier one for context.

2022-07-27 14:05 UTC, kylelaker approved these changes
Nice! This is looking good! Thank you@

2022-07-27 14:07 UTC, kylelaker commented on .github/workflows/triage-pr.yml
> +              "pull_requests": "write"
```suggestion
              "pull_requests": "write",
              "members": "read",
```

2022-07-27 14:07 UTC, kylelaker approved these changes

2022-07-27 18:39 UTC, Bronstrom approved these changes

2022-07-27 18:39 UTC, merged