Make Citations, titles and, descriptions appear in markdown
EasyDynamics/oscal-react-library pull request #556
Opened 2022-08-10 16:01 UTC by schen2166

The Backmatter has markup language shown in prose in the screenshots below. Wrap them in a `OSCALMarkupProse` component so that it is easier for users to read.
<img src = "https://user-images.githubusercontent.com/106985986/183956830-aa5ad573-456b-4aa3-8ead-201248b6ce01.png"><br/><img src="https://user-images.githubusercontent.com/106985986/183957500-d053710d-1a3b-4182-9cd2-9fc62e421af5.png">

2022-08-10 16:06 UTC, schen2166 commented
This screenshot shows that the Title, and citation descriptions have been updated to be shown in markdown.
<img src ="https://user-images.githubusercontent.com/106985986/183958572-0bf4f2f5-a03d-453c-8c06-fc958f4fa854.png">

2022-08-10 23:23 UTC, kylelaker requested changes

2022-08-10 23:23 UTC, kylelaker commented on src/components/OSCALBackMatter.js
> +      title={<OSCALMarkupLine text={props.resource.description} />}
`description` is `markup-multiline`: https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/back-matter/resources/description

2022-08-11 18:46 UTC, tuckerzp commented on src/components/OSCALBackMatter.js
> +      <OSCALMarkupLine text={title} />
```suggestion
      <OSCALMarkupLine>{title}</OSCALMarkupLine>
```

2022-08-11 19:19 UTC, kperk103 commented on src/components/OSCALBackMatter.js
> +      <OSCALMarkupLine text={title} />
The most recent commit addresses this

2022-08-11 22:02 UTC, kylelaker approved these changes

2022-08-11 22:07 UTC, Bronstrom approved these changes

2022-08-11 22:07 UTC, merged