Automatically add issues to the project board
EasyDynamics/oscal-react-library pull request #645
Opened 2023-01-19 16:21 UTC by tuckerzp

To help track issues created on the oscal react library,
this will automatically add the issue to our project board.

2023-01-23 16:15 UTC, kylelaker requested changes

2023-01-23 16:15 UTC, kylelaker commented on .github/workflows/add-to-project.yml
> +          private_key: ${{ secrets.APP_PRIVATE_KEY }}
We should scope down the permissions on this first and also use v1.7.0.

2023-01-24 17:38 UTC, Bronstrom approved these changes

2023-01-24 17:42 UTC, kylelaker approved these changes

2023-01-24 17:42 UTC, merged