chore(revisions): Create not specified style
EasyDynamics/oscal-react-library pull request #790
Opened 2023-04-21 16:03 UTC by tuckerzp

2023-04-21 16:09 UTC, Bronstrom approved these changes

2023-04-21 17:55 UTC, kylelaker requested changes

2023-04-21 17:55 UTC, kylelaker commented on packages/oscal-react-library/src/components/OSCALRevision.tsx
> +})) as typeof Typography;
Can you put this in a central place and export it? And search for other places where `Not specified` or `No <thing>` appear and use this there?

2023-04-24 20:09 UTC, kylelaker approved these changes

2023-04-24 20:09 UTC, merged